package ffmpeg

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/hekmon/processpriority"
)

const (
	concatScriptHeader = "ffconcat version 1.0"
)

// ConcatListPath is the path to an ffconcat script generated by GenerateConcatList.
type ConcatListPath string

// GenerateConcatList creates an ffconcat script in dir that references files.
// It returns the generated script's path and any error.
func GenerateConcatList(dir string, files []string) (scriptPath ConcatListPath, err error) {
	if len(files) == 0 {
		err = fmt.Errorf("no files to concatenate")
		return
	}
	// Create file
	scriptPath = ConcatListPath(filepath.Join(dir, fmt.Sprintf("list-%d.ffconcat", time.Now().Nanosecond())))
	script, err := os.Create(string(scriptPath))
	if err != nil {
		err = fmt.Errorf("failed to create the file: %w", err)
		return
	}
	defer script.Close()
	// Write header
	if _, err = fmt.Fprintln(script, concatScriptHeader); err != nil {
		err = fmt.Errorf("failed to write the header: %w", err)
		return
	}
	// Write files' path
	var absPath string
	for _, file := range files {
		// Relative paths are resolved by ffmpeg against the list file directory, not
		// the current working directory: always write absolute paths.
		if absPath, err = filepath.Abs(file); err != nil {
			err = fmt.Errorf("failed to get the absolute path of %q: %w", file, err)
			return
		}
		// Within single quotes ffmpeg takes everything literally (backslashes included):
		// the only special character is the quote itself, which must be written by closing
		// the quoting, adding an escaped quote and reopening the quoting.
		escapedPath := strings.ReplaceAll(absPath, `'`, `'\''`)
		if _, err = fmt.Fprintf(script, "file '%s'\n", escapedPath); err != nil {
			err = fmt.Errorf("failed to write the file: %w", err)
			return
		}
	}
	return
}

// ConcatConfig holds the configuration for the Concat operation.
type ConcatConfig struct {
	// Input / output
	ConcatListPath ConcatListPath
	ConcatUnsafe   bool
	OutputPath     string
	// Reporting
	Debug             func(msg string)
	RuntimeError      func(err error) // non fatal errors
	FFMPEGStatsReport func(stats ProgressStats)
}

// Concat runs ffmpeg to concatenate segments using the provided config.
func Concat(ctx context.Context, config ConcatConfig) (err error) {
	// Validate inputs
	if config.ConcatListPath == "" {
		return errors.New("concat script path cannot be empty")
	}
	if config.OutputPath == "" {
		return errors.New("output path cannot be empty")
	}
	// Prepare args
	var args []string
	args = append(args,
		"-y", "-loglevel", "error", "-nostats", "-progress", "pipe:1", "-stats_period",
		strconv.FormatFloat(float64(StatsPeriod)/float64(time.Second), 'f', -1, 64),
	)
	if config.ConcatUnsafe {
		args = append(args, "-safe", "0")
	}
	args = append(args,
		"-i", string(config.ConcatListPath),
		"-c", "copy",
		config.OutputPath,
	)
	// Prepare command
	if config.Debug != nil {
		config.Debug(fmt.Sprintf("Concat segments with: %s", getPrintableCMDLine(FFMPEGBinary, args)))
	}
	cmd := exec.CommandContext(ctx, FFMPEGBinary, args...)
	// Prepare output handling
	stdoutPipe, err := cmd.StdoutPipe()
	if err != nil {
		err = fmt.Errorf("error setting up stdout pipe: %w", err)
		return
	}
	stderrPipe, err := cmd.StderrPipe()
	if err != nil {
		err = fmt.Errorf("error setting up stderr pipe: %w", err)
		return
	}
	// Start program
	if err = cmd.Start(); err != nil {
		err = fmt.Errorf("error starting %s: %w\n%s", FFMPEGBinary, err, getPrintableCMDLine(FFMPEGBinary, args))
		return
	}
	// Start progress monitoring (after cmd.Start to avoid goroutine leak on error)
	progressDone := make(chan struct{})
	go func() {
		standardProgress(stdoutPipe, config.FFMPEGStatsReport, config.RuntimeError)
		close(progressDone)
	}()
	stderrDone := make(chan struct{})
	go func() {
		stderrForwarder(stderrPipe, config.RuntimeError)
		close(stderrDone)
	}()
	if err = processpriority.Set(cmd.Process.Pid, ProcessPriority); err != nil && config.RuntimeError != nil {
		config.RuntimeError(fmt.Errorf("Failed to lower %s process priority: %w", FFMPEGBinary, err))
	}
	<-progressDone
	<-stderrDone
	if err = cmd.Wait(); err != nil {
		err = fmt.Errorf("error during %s execution: %w\n%s", FFMPEGBinary, err, getPrintableCMDLine(FFMPEGBinary, args))
		return
	}
	return
}
