package ffmpeg

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/hekmon/processpriority"
)

const (
	concatScriptHeader = "ffconcat version 1.0"
)

// ConcatListPath is the path to an ffconcat script generated by GenerateConcatList.
type ConcatListPath string

// GenerateConcatList creates an ffconcat script in dir that references files, each one
// with its duration when durations is given (aligned with files, nil for none).
// It returns the generated script's path and any error.
//
// # WHY A DURATION PER FILE
//
// The concat demuxer starts each file where the previous one ends, and takes that point
// from the previous file's duration. Without a duration line, that duration is the one the
// container declares, which for a Matroska file is its last timestamp plus its last frame
// duration, both rounded to the millisecond. At 23.976 fps the last frame always counts for
// 42 ms instead of 41.708: an encoded segment claims 0.3 ms more than its frames last on
// average, from 0.17 ms less to 0.79 ms more depending on how its last timestamp was rounded
// (measured on every length: a 20 frames segment declares 834 ms for 834.167 ms of frames,
// a 13 frames one 543 ms for 542.208 ms). The excess is never compensated: it adds up at
// every boundary, and the video drifts behind the other tracks by about 0.3 ms per segment
// (46 ms measured at the end of a 163 segments episode, a quarter of a second on a film cut
// in 800). With a duration line the demuxer
// uses that value instead, and the callers compute it from what they know exactly: the
// frame count of each file and the frame rate. The start it computes out of them is still
// rounded to the time base of the stream: see Concat for what that does to the frames.
//
// # WHY NOT KEEPING THE SEGMENTS' ORIGINAL TIMESTAMPS
//
// Splitting without -reset_timestamps leaves each segment with the timestamps it had in
// the source, but the demuxer offsets every file by the previous durations all the same,
// so the drift is identical (measured). Only the duration line changes the arithmetic.
//
// # EDGE CASES
//
// The duration of the last file only affects the total duration reported for the list, not
// any offset. Durations are written in seconds with 6 decimals, the microsecond precision
// the demuxer parses them with.
func GenerateConcatList(dir string, files []string, durations []time.Duration) (scriptPath ConcatListPath, err error) {
	if len(files) == 0 {
		err = fmt.Errorf("no files to concatenate")
		return
	}
	if durations != nil && len(durations) != len(files) {
		err = fmt.Errorf("%d durations given for %d files", len(durations), len(files))
		return
	}
	// Create file
	scriptPath = ConcatListPath(filepath.Join(dir, fmt.Sprintf("list-%d.ffconcat", time.Now().Nanosecond())))
	script, err := os.Create(string(scriptPath))
	if err != nil {
		err = fmt.Errorf("failed to create the file: %w", err)
		return
	}
	defer script.Close()
	// Write header
	if _, err = fmt.Fprintln(script, concatScriptHeader); err != nil {
		err = fmt.Errorf("failed to write the header: %w", err)
		return
	}
	// Write files' path
	var absPath string
	for i, file := range files {
		// Relative paths are resolved by ffmpeg against the list file directory, not
		// the current working directory: always write absolute paths.
		if absPath, err = filepath.Abs(file); err != nil {
			err = fmt.Errorf("failed to get the absolute path of %q: %w", file, err)
			return
		}
		// Within single quotes ffmpeg takes everything literally (backslashes included):
		// the only special character is the quote itself, which must be written by closing
		// the quoting, adding an escaped quote and reopening the quoting.
		escapedPath := strings.ReplaceAll(absPath, `'`, `'\''`)
		if _, err = fmt.Fprintf(script, "file '%s'\n", escapedPath); err != nil {
			err = fmt.Errorf("failed to write the file: %w", err)
			return
		}
		if durations != nil {
			if durations[i] < 0 {
				err = fmt.Errorf("negative duration %s for %q", durations[i], file)
				return
			}
			if _, err = fmt.Fprintf(script, "duration %s\n", strconv.FormatFloat(durations[i].Seconds(), 'f', 6, 64)); err != nil {
				err = fmt.Errorf("failed to write the duration: %w", err)
				return
			}
		}
	}
	return
}

// ConcatConfig holds the configuration for the Concat operation.
type ConcatConfig struct {
	// Input / output
	ConcatListPath ConcatListPath
	ConcatUnsafe   bool
	OutputPath     string
	// FrameRate of the video, as ffprobe writes r_frame_rate ("24000/1001", "25"): the video
	// timestamps are snapped to its frame grid, see Concat (and frameGridSnap for which rate).
	// Empty, they are copied as the demuxer computes them.
	FrameRate string
	// Reporting
	Debug             func(msg string)
	RuntimeError      func(err error) // non fatal errors
	FFMPEGStatsReport func(stats ProgressStats)
}

// Concat runs ffmpeg to concatenate segments using the provided config. When config.FrameRate
// is given, the video timestamps of the output are snapped to its frame grid (see
// frameGridSnap).
//
// # WHY THE TIMESTAMPS ARE SNAPPED
//
// The duration lines of the list (see GenerateConcatList) give the demuxer the exact start
// of every file, but it rounds that start to the time base of the stream, the millisecond
// in Matroska, and adds it to timestamps that were already rounded from the file's own
// start: an encoder does not keep the timestamps of the segment it is given, it numbers the
// frames from 0 at the frame rate and the muxer rounds each of them to the millisecond.
// Rounded twice, a frame lands up to 1 ms away from its exact time, where a single rounding
// (the master's) keeps it within half a millisecond. At 23.976 fps, take a segment from
// frame 26 to 76: it starts at 1084.417 ms, rounded to 1084, and its last frame comes
// 2085.417 ms later, rounded to 2085. That frame is written at 3169 ms, where the master has
// it at 3170 (3169.833 ms rounded once), and the next segment starts at 3211.542 ms, rounded
// to 3212: the frame lasts 43 ms instead of 41 or 42. FFProbeBinaryStream.IsConstantFrameRate
// then reports a variable frame rate: `sptenc vmaf` refused sptenc's own outputs, and so did
// `sptenc master` when given one back. With the segment lengths of real content it hits most
// files (about 94% of simulated 23.976 fps episodes of 163 segments); 29.97 and 59.94 fps
// are hit the same way, 25 and 50 fps never are, their frames lasting whole milliseconds.
//
// Snapping moves every timestamp to the exact time of its frame rounded once, where the
// master has it. The duration lines are needed all the same: the snap only finds the right
// frame for a timestamp less than half a frame away from it, and without them the offsets
// drift at every boundary (about 0.3 ms at 23.976 fps, 46 ms over 163 segments).
//
// # WHY NOT A LARGER TOLERANCE IN THE CHECK INSTEAD
//
// The check is right: the file is not what a single rounding of the master gives, and sptenc
// promises the frames back with their timing. A tolerance letting a 43 ms frame through would
// let a mix of 24 and 25 fps through as well: its frames last from 40 to 42 ms, the same
// 2 ms spread (see IsConstantFrameRate).
//
// # WHY NOT KEEPING EXACT TIMESTAMPS IN THE SEGMENTS INSTEAD
//
// Two ways were measured exact with software encoders, but both move the fix from the one
// place where the segments meet to every encode:
//   - Encoded segments stored in a container whose time base is the frame duration (NUT,
//     MP4) keep exact timestamps, only the final Matroska mux rounds them, once. Every tool
//     reading the segments changes with them, MP4 needs edit lists for B-frames, and an
//     interrupted MP4 encode leaves an unreadable file.
//   - Encodes keeping the source timestamps (-copyts), with duration lines computed from the
//     actual first timestamp of each segment. Every encoder has to honor it, hardware ones
//     included, which was not tested.
func Concat(ctx context.Context, config ConcatConfig) (err error) {
	// Validate inputs
	if config.ConcatListPath == "" {
		return errors.New("concat script path cannot be empty")
	}
	if config.OutputPath == "" {
		return errors.New("output path cannot be empty")
	}
	var snap string
	if config.FrameRate != "" {
		if snap, err = frameGridSnap(config.FrameRate); err != nil {
			return
		}
	}
	// Prepare args
	var args []string
	args = append(args,
		"-y", "-loglevel", "error", "-nostats", "-progress", "pipe:1", "-stats_period",
		strconv.FormatFloat(float64(StatsPeriod)/float64(time.Second), 'f', -1, 64),
	)
	if config.ConcatUnsafe {
		args = append(args, "-safe", "0")
	}
	args = append(args,
		"-i", string(config.ConcatListPath),
		"-c", "copy",
	)
	if snap != "" {
		args = append(args, "-bsf:v", snap)
	}
	args = append(args, config.OutputPath)
	// Prepare command
	if config.Debug != nil {
		config.Debug(fmt.Sprintf("Concat segments with: %s", getPrintableCMDLine(FFMPEGBinary, args)))
	}
	cmd := exec.CommandContext(ctx, FFMPEGBinary, args...)
	// Prepare output handling
	stdoutPipe, err := cmd.StdoutPipe()
	if err != nil {
		err = fmt.Errorf("error setting up stdout pipe: %w", err)
		return
	}
	stderrPipe, err := cmd.StderrPipe()
	if err != nil {
		err = fmt.Errorf("error setting up stderr pipe: %w", err)
		return
	}
	// Start program
	if err = cmd.Start(); err != nil {
		err = fmt.Errorf("error starting %s: %w\n%s", FFMPEGBinary, err, getPrintableCMDLine(FFMPEGBinary, args))
		return
	}
	// Start progress monitoring (after cmd.Start to avoid goroutine leak on error)
	progressDone := make(chan struct{})
	go func() {
		standardProgress(stdoutPipe, config.FFMPEGStatsReport, config.RuntimeError)
		close(progressDone)
	}()
	stderrDone := make(chan struct{})
	go func() {
		stderrForwarder(stderrPipe, config.RuntimeError)
		close(stderrDone)
	}()
	if err = processpriority.Set(cmd.Process.Pid, ProcessPriority); err != nil && config.RuntimeError != nil {
		config.RuntimeError(fmt.Errorf("Failed to lower %s process priority: %w", FFMPEGBinary, err))
	}
	<-progressDone
	<-stderrDone
	if err = cmd.Wait(); err != nil {
		err = fmt.Errorf("error during %s execution: %w\n%s", FFMPEGBinary, err, getPrintableCMDLine(FFMPEGBinary, args))
		return
	}
	return
}

// frameGridSnap returns the setts bitstream filter snapping the pts and dts of a video stream
// numbered at frameRate (as ffprobe writes r_frame_rate: "24000/1001", "25") to its frame
// grid: each timestamp becomes the index of the nearest frame, then the exact time of that
// frame rounded to the stream time base (TB), halves away from zero as ffmpeg's rescaling
// does, the one that wrote the master's timestamps. setts has no frame rate variable: the
// rate is written into the expression.
//
// # EDGE CASES
//
//   - The grid starts at 0, where the first frame of the first segment is: segments are cut
//     with their timestamps reset and encoded from 0.
//   - Decode timestamps (starting before 0 with B-frames) are snapped by the same function,
//     which never swaps two timestamps: they stay increasing and never after their
//     presentation timestamp.
//   - setts evaluates every packet, the ones without a timestamp too: a missing timestamp
//     (NOPTS, the lowest int64, not a time) is kept missing instead of being computed with.
//     This takes commas, which separate the filters of a bitstream filter list: each
//     expression is quoted.
//   - A timestamp already exact (25 fps, or a file snapped before) comes out unchanged.
//   - The computation is done in double precision, the order of the operations keeps it
//     exact however far into the file, halves included (see TestFrameGridSnap_Exact).
//   - The frame rate must be the exact one of the frames, the master's, which is not always
//     the one the segments declare: a 59.94 fps Matroska file reads as 19001/317, not
//     60000/1001 (see core.SameFrameRate), while a master made from a source that is not
//     Matroska is numbered at the exact rate. Snapped at 19001/317, the output was 1 ms before
//     that master on one frame in 60 (measured), more as the two rates drift apart (0.19 ms
//     per hour). The pipeline gives the source's rate (see core.QPSearchConfig.SourceFrameRate),
//     and the snap puts back the frames the encoders numbered at the approximation: within a
//     segment the two grids drift apart by 0.9 ns per frame at 59.94 fps and 3.2 ns at 119.88,
//     corrected while under half a frame (8.3 and 4.2 ms).
func frameGridSnap(frameRate string) (bsf string, err error) {
	num, den, err := frameRateFraction(frameRate)
	if err != nil {
		return "", fmt.Errorf("invalid frame rate %q: %w", frameRate, err)
	}
	snap := func(timestamp string) string {
		// index of the nearest frame, then the time of that frame in TB units
		return fmt.Sprintf("'if(eq(%[1]s,NOPTS),NOPTS,round(round(%[1]s*TB*%[2]d/%[3]d)*%[3]d/TB/%[2]d))'",
			timestamp, num, den)
	}
	return "setts=pts=" + snap("PTS") + ":dts=" + snap("DTS"), nil
}

// frameRateFraction parses a frame rate written as ffprobe writes r_frame_rate, "num/den" or
// "num" (den 1), into positive integers. It accepts what core.FramesDuration accepts: both
// are given the same QPSearchResults.FrameRate.
func frameRateFraction(frameRate string) (num, den int64, err error) {
	numStr, denStr, isFraction := strings.Cut(frameRate, "/")
	if !isFraction {
		denStr = "1"
	}
	if num, err = strconv.ParseInt(strings.TrimSpace(numStr), 10, 64); err != nil {
		return 0, 0, fmt.Errorf("invalid numerator %q: %w", numStr, err)
	}
	if den, err = strconv.ParseInt(strings.TrimSpace(denStr), 10, 64); err != nil {
		return 0, 0, fmt.Errorf("invalid denominator %q: %w", denStr, err)
	}
	if num <= 0 || den <= 0 {
		return 0, 0, fmt.Errorf("frame rate %d/%d is not positive", num, den)
	}
	return
}
